name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/full-stack-assignment:latest .

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/full-stack-assignment:latest

      - name: SSH to EC2 and update container
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/full-stack-assignment:latest
            
            docker stop full-stack-assignment || true
            docker rm full-stack-assignment || true
              
            docker run -d -p 3000:3000 \
              --name full-stack-assignment \
              --env-file /home/ubuntu/full-stack-assignment/.env \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/full-stack-assignment:latest